name: Update README with Latest Tech News

on:
  schedule:
    - cron: "*/5 * * * *"  # Chạy mỗi 5 phút

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: 'tcdtist/daily-tech-digest'
          ref: 'main'

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt 

      - name: Update README
        env:
          GNEWS_API_KEY: ${{ secrets.GNEWS_API_KEY }}
        run: python fetch_news.py

      # --- Thay đổi phần Commit và Push sử dụng GITHUB_TOKEN ---
      - name: Commit changes
        uses: EndBug/add-and-commit@v9 # Sử dụng action tiện lợi
        with:
          author_name: tcdtist
          author_email: chithanh.tist@gmail.com
          message: "Updated README with latest tech news"
          add: README.md
          push: true # Thêm tùy chọn này để đẩy lên GitHub

      # --- Loại bỏ các bước liên quan đến SSH ---
